CREATE TABLE User (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    FIRST_NAME varchar(255) NOT NULL,
    LAST_NAME varchar(255) NOT NULL,
    EMAIL varchar(255) NOT NULL UNIQUE,
    ADDRESS varchar(255) NOT NULL,
    BIRTH_DATE date NOT NULL,
    PRIMARY KEY (ID)
);